# yaml-language-server: $schema=../schemas/config.editor.schema.json#/$defs/AuthSettings
api_key_cache:
  capacity: 1024
  ttl: 1h
oauth:
  issuer: https://idm.anurag.sh/oauth2/openid/home-gateway
  jwks_url: https://idm.anurag.sh/oauth2/openid/home-gateway/public_key.jwk
  userinfo_url: https://idm.anurag.sh/oauth2/openid/home-gateway/userinfo
  audience: home-gateway
  cache:
    keys:
      capacity: 32
      ttl: 1h
    userinfo:
      capacity: 256
      ttl: 15m
  group_scopes:
    home_gateway_admins@idm.anurag.sh: ["**:*"]
    home_gateway_readers@idm.anurag.sh:
      - "*:read"
      - "media.player:read"
      - "events.**:read"
api_keys:
  - name: eink-display-living-room
    scopes: ["epd:read"]
  - name: unifi-ingest
    scopes: ["ingest.unifi:write"]
  - name: home-gateway-app
    scopes: ["**:*"]
  - name: home-ui
    scopes: ["**:*"]
  - name: oled-remote
    scopes:
      - "light:read"
      - "light:write"
      - "media.player:read"
      - "media.player:write"
