# yaml-language-server: $schema=../schemas/config.editor.schema.json#/$defs/MqttSettings
port: 1883
keep_alive: 5s
max_packet_size: 100000
channel_capacity: 100
reconnect:
  min: 1s
  max: 60s
models: lua/mqtt
protocols:
  zigbee:
    topics:
      report: "zigbee2mqtt/{name}"
    command: "zigbee2mqtt/{name}/set"
    directory: "zigbee2mqtt/bridge/devices"
  esphome:
    topics:
      state: "{address}/{domain}/{object_id}/state"
    command: "{address}/{domain}/{object_id}/command"
    discovery: "esphome/discover/{address}"
  valetudo:
    topics:
      state: "valetudo/{address}/state"
      attributes: "valetudo/{address}/attributes"
    command: "valetudo/{address}/command"
