# yaml-language-server: $schema=../schemas/config.editor.schema.json#/$defs/MqttSettings
port: 1883
keep_alive: 5s
max_packet_size: 100000
channel_capacity: 100
reconnect:
  min: 1s
  max: 60s
models: lua/mqtt
protocols:
  zigbee:
    payload: json
    address_path: [device, ieee_addr]
    entities: disabled
    roles: [battery, door, environment, light, smart_switch, presence, control_switch]
    topics:
      report: "zigbee2mqtt/{name}"
    command: "zigbee2mqtt/{name}/set"
    directory: "zigbee2mqtt/bridge/devices"
  esphome:
    payload: esphome_domain
    entities: enabled
    roles: [battery, environment, plant, light, presence]
    topics:
      state: "{address}/{domain}/{object_id}/state"
    command: "{address}/{domain}/{object_id}/command"
    discovery: "esphome/discover/{address}"
  valetudo:
    payload: json
    entities: disabled
    roles: [robot_vacuum, battery]
    topics:
      state: "valetudo/{address}/state"
      attributes: "valetudo/{address}/attributes"
    command: "valetudo/{address}/command"
