# yaml-language-server: $schema=../schemas/workflows.schema.json
- name: Control Switch
  slug: control-switch
  group: Control Switch
  on: { type: switch, device: control-switch }
  modes: [home, away, guest]
  run:
    - type: lua
      call: buttons.dispatch
      returns: {}
      args:
        - table-lamp-bedroom
        - on: { state: ON }
          off: { state: OFF }
          brightness_move_up: { state: INCREASE_BRIGHTNESS, value: 75 }
          brightness_move_down: { state: DECREASE_BRIGHTNESS, value: 75 }
          brightness_stop: { state: STOP_BRIGHTNESS }
          arrow_right_hold: { state: INCREASE_COLOUR_TEMPERATURE, value: 120 }
          arrow_left_hold: { state: DECREASE_COLOUR_TEMPERATURE, value: 120 }
          arrow_left_release: { state: STOP_COLOUR_TEMPERATURE }
          arrow_right_release: { state: STOP_COLOUR_TEMPERATURE }
          arrow_left_click: { state: SET_BRIGHTNESS, value: 50 }
          arrow_right_click: { state: SET_BRIGHTNESS, value: 254 }
