- name: Control Switch on
  slug: control-switch-on
  group: Control Switch
  on: { type: switch, device: control-switch, action: on }
  run:
    - type: light
      device: table-lamp-bedroom
      state: ON

- name: Control Switch off
  slug: control-switch-off
  group: Control Switch
  on: { type: switch, device: control-switch, action: off }
  run:
    - type: light
      device: table-lamp-bedroom
      state: OFF

- name: Control Switch brightness up
  slug: control-switch-brightness-up
  group: Control Switch
  on: { type: switch, device: control-switch, action: brightness_move_up }
  run:
    - type: light
      device: table-lamp-bedroom
      state: INCREASE_BRIGHTNESS
      value: 75

- name: Control Switch brightness down
  slug: control-switch-brightness-down
  group: Control Switch
  on: { type: switch, device: control-switch, action: brightness_move_down }
  run:
    - type: light
      device: table-lamp-bedroom
      state: DECREASE_BRIGHTNESS
      value: 75

- name: Control Switch brightness stop
  slug: control-switch-brightness-stop
  group: Control Switch
  on: { type: switch, device: control-switch, action: brightness_stop }
  run:
    - type: light
      device: table-lamp-bedroom
      state: STOP_BRIGHTNESS

- name: Control Switch colour temp up
  slug: control-switch-colour-temp-up
  group: Control Switch
  on: { type: switch, device: control-switch, action: arrow_right_hold }
  run:
    - type: light
      device: table-lamp-bedroom
      state: INCREASE_COLOUR_TEMPERATURE
      value: 120

- name: Control Switch colour temp down
  slug: control-switch-colour-temp-down
  group: Control Switch
  on: { type: switch, device: control-switch, action: arrow_left_hold }
  run:
    - type: light
      device: table-lamp-bedroom
      state: DECREASE_COLOUR_TEMPERATURE
      value: 120

- name: Control Switch colour temp stop left
  slug: control-switch-colour-temp-stop-left
  group: Control Switch
  on: { type: switch, device: control-switch, action: arrow_left_release }
  run:
    - type: light
      device: table-lamp-bedroom
      state: STOP_COLOUR_TEMPERATURE

- name: Control Switch colour temp stop right
  slug: control-switch-colour-temp-stop-right
  group: Control Switch
  on: { type: switch, device: control-switch, action: arrow_right_release }
  run:
    - type: light
      device: table-lamp-bedroom
      state: STOP_COLOUR_TEMPERATURE

- name: Control Switch set brightness low
  slug: control-switch-set-brightness-low
  group: Control Switch
  on: { type: switch, device: control-switch, action: arrow_left_click }
  run:
    - type: light
      device: table-lamp-bedroom
      state: SET_BRIGHTNESS
      value: 50

- name: Control Switch set brightness high
  slug: control-switch-set-brightness-high
  group: Control Switch
  on: { type: switch, device: control-switch, action: arrow_right_click }
  run:
    - type: light
      device: table-lamp-bedroom
      state: SET_BRIGHTNESS
      value: 254
