- name: living-room-lamps-on
  slug: living-room-lamps-on
  group: Living Room
  run:
    - type: light
      when: { type: light, device: floor-lamp-living-room, on: false }
      device: floor-lamp-living-room
      state: ON
    - type: light
      device: living-room-table-lamp
      state: ON

- name: living-room-lamps-off
  slug: living-room-lamps-off
  group: Living Room
  run:
    - type: light
      device: floor-lamp-living-room
      state: OFF
    - type: light
      device: living-room-table-lamp
      state: OFF

- name: Living room lamp on (occupancy after sunset)
  slug: living-room-lamp-on-occupancy
  group: Living Room
  tags: [living-room]
  on: { type: presence, sensor: livingroom-motion, present: true }
  when: { type: sun, is: night }
  run:
    - type: run_workflow
      workflow: living-room-lamps-on

- name: Living room lamp on (sunset while occupied)
  slug: living-room-lamp-on-sunset
  group: Living Room
  tags: [living-room]
  on: { type: sun, transition: sunset }
  when: { type: presence, sensor: livingroom-motion, present: true }
  run:
    - type: scene
      when: { type: light, device: floor-lamp-living-room, on: false }
      run:
        - type: light
          device: floor-lamp-living-room
          state: SET_BRIGHTNESS
          value: 1
        - type: light
          device: floor-lamp-living-room
          state: INCREASE_BRIGHTNESS
          value: 1
    - type: light
      device: living-room-table-lamp
      state: ON

- name: Living room lamp off (no occupancy)
  slug: living-room-lamp-off
  group: Living Room
  tags: [living-room]
  on: { type: presence, sensor: livingroom-motion, present: false }
  delay: 25m
  run:
    - type: run_workflow
      workflow: living-room-lamps-off
