mutation LightOn($id: IdOrAlias!) {
  light(id: $id) {
    on
  }
}

mutation LightOff($id: IdOrAlias!) {
  light(id: $id) {
    off
  }
}

mutation LightSetBrightness($id: IdOrAlias!, $value: Int!) {
  light(id: $id) {
    setBrightness(input: { value: $value })
  }
}

mutation LightSetColourTemperature($id: IdOrAlias!, $value: Int!) {
  light(id: $id) {
    setColourTemperature(input: { value: $value })
  }
}

mutation MediaPlayPause($id: IdOrAlias!) {
  mediaPlayer(id: $id) {
    playPause
  }
}

mutation MediaStop($id: IdOrAlias!) {
  mediaPlayer(id: $id) {
    stop
  }
}

mutation VacuumStart($id: IdOrAlias!) {
  robotVacuum(id: $id) {
    start
  }
}

mutation VacuumStop($id: IdOrAlias!) {
  robotVacuum(id: $id) {
    stop
  }
}

mutation VacuumDock($id: IdOrAlias!) {
  robotVacuum(id: $id) {
    dock
  }
}

mutation EinkTakeScreenshot($id: IdOrAlias!) {
  einkDisplay(id: $id) {
    takeScreenshot
  }
}
