s3:
  bucket: home-gateway-bucket
  region: ap-southeast-2

devices:
  closet_light: "0x54ef441000d4f05c"
  non_existent_light: "0x000000000000000"
  ceiling_light: "0x001788010381ef5d"
  desk_lamp: "0x94a081fffe2eedc0"
  closet_presence: "0x54ef441000dbc81c"

notify_targets:
  home:
    type: android_app

fcm_project_id: home-gateway-22

reminders:
  - id: bins
    name: Bins
    starts_on: 2025-07-17T20:00:00.0+08:00
    frequency: every 1 week
    state: active
    notify:
      - home

doors:
  "0x54ef441000d2b0b0":
    name: Front Door
    id: FRONT_DOOR
    state: armed
    timeout: 3m
    notify:
      - home

maccas:
  offers: []

appliances:
  "0xa4c1389fe5cea26e":
    name: Washing Machine
    id: WASHING_MACHINE
    current:
      threshold: 0.05
    notify:
      - home

temperature_sensors:
  - id: LAUNDRY
    source: { zigbee: "0x00158d008b8797bc" }
  - id: LIVING_ROOM
    source: { zigbee: "0x00158d008b8798a7" }
  - id: BATHROOM
    source: { zigbee: "0x00158d008b879b53" }
  - id: BEDROOM
    source: { zigbee: "0xb0c7defffef6a9be" }
  - id: OUTDOOR
    source: { zigbee: "0x54ef441000ee2ca3" }
  - id: LIVING_ROOM_MTR
    source: { esphome: { node: apollo-mtr-1-livingroom } }

presence_sensors:
  - name: Closet Presence Sensor
    source: { zigbee: closet_presence }
    actions:
      PresenceDetected:
        - type: light
          device: closet_light
          state: ON
      NoPresenceDetected:
        - type: light
          device: closet_light
          state: OFF

  - name: Living Room Motion
    source:
      esphome:
        node: apollo-mtr-1-livingroom
        motion_entity: ld2450_moving_target
    actions:
      PresenceDetected:
        - type: light
          device: non_existent_light
          state: ON
      NoPresenceDetected:
        - type: light
          device: non_existent_light
          state: OFF

switches:
  "0x00158d008bbe0316":
    name: Small Switch
    actions:
      single:
        - type: light
          device: desk_lamp
          state: TOGGLE

  "0x64028ffffe638218":
    name: Control Switch
    actions:
      on:
        - type: light
          device: ceiling_light
          state: ON

      off:
        - type: light
          device: ceiling_light
          state: OFF

      brightness_move_up:
        - type: light
          device: ceiling_light
          state: INCREASE_BRIGHTNESS
          value: 75

      brightness_move_down:
        - type: light
          device: ceiling_light
          state: DECREASE_BRIGHTNESS
          value: 75

      brightness_stop:
        - type: light
          device: ceiling_light
          state: STOP_BRIGHTNESS

      arrow_right_hold:
        - type: light
          device: ceiling_light
          state: INCREASE_COLOUR_TEMPERATURE
          value: 120

      arrow_left_hold:
        - type: light
          device: ceiling_light
          state: DECREASE_COLOUR_TEMPERATURE
          value: 120

      arrow_left_release:
        - type: light
          device: ceiling_light
          state: STOP_COLOUR_TEMPERATURE

      arrow_right_release:
        - type: light
          device: ceiling_light
          state: STOP_COLOUR_TEMPERATURE

      arrow_left_click:
        - type: light
          device: ceiling_light
          state: SET_BRIGHTNESS
          value: 50

      arrow_right_click:
        - type: light
          device: ceiling_light
          state: SET_BRIGHTNESS
          value: 254
