switches:
  "0x64028ffffe638218":
    name: Control Switch
    actions:
      on:
        workflow:
          run:
            - type: light
              ieeeAddr: "0x001788010381ef5d"
              state: ON

      off:
        workflow:
          run:
            - type: light
              ieeeAddr: "0x001788010381ef5d"
              state: OFF

      brightness_move_up:
        workflow:
          run:
            - type: light
              ieeeAddr: "0x001788010381ef5d"
              state: INCREASE_BRIGHTNESS
              value: 75

      brightness_move_down:
        workflow:
          run:
            - type: light
              ieeeAddr: "0x001788010381ef5d"
              state: DECREASE_BRIGHTNESS
              value: 75

      brightness_stop:
        workflow:
          run:
            - type: light
              ieeeAddr: "0x001788010381ef5d"
              state: STOP_BRIGHTNESS

      arrow_right_hold:
        workflow:
          run:
            - type: light
              ieeeAddr: "0x001788010381ef5d"
              state: INCREASE_COLOUR_TEMPERATURE
              value: 120

      arrow_left_hold:
        workflow:
          run:
            - type: light
              ieeeAddr: "0x001788010381ef5d"
              state: DECREASE_COLOUR_TEMPERATURE
              value: 120

      arrow_left_release:
        workflow:
          run:
            - type: light
              ieeeAddr: "0x001788010381ef5d"
              state: STOP_COLOUR_TEMPERATURE

      arrow_right_release:
        workflow:
          run:
            - type: light
              ieeeAddr: "0x001788010381ef5d"
              state: STOP_COLOUR_TEMPERATURE

      # arrow_left_click
      # arrow_right_click
