apiVersion: v1
kind: Service
metadata:
  name: selfbot
  namespace: home-gateway
spec:
  selector:
    app: selfbot
  ports:
    - name: proxy
      protocol: TCP
      port: 80
      targetPort: 8004
