mod cron_variables;
mod device_battery_variables;
mod door_variables;
mod environment_variables;
mod fuel_watch_variables;
mod home_assistant_variables;
mod jellyfin_variables;
mod media_player_variables;
mod mode_variables;
mod presence_variables;
mod solar_variables;
mod sun_variables;
mod switch_variables;
mod weather_variables;
mod woolworths_variables;

pub use cron_variables::CronVariables;
pub use device_battery_variables::DeviceBatteryVariables;
pub use door_variables::DoorVariables;
pub use environment_variables::EnvironmentVariables;
pub use fuel_watch_variables::FuelWatchVariables;
pub use home_assistant_variables::HomeAssistantVariables;
pub use jellyfin_variables::JellyfinVariables;
pub use media_player_variables::MediaPlayerVariables;
pub use mode_variables::ModeVariables;
pub use presence_variables::PresenceVariables;
pub use solar_variables::SolarVariables;
pub use sun_variables::SunVariables;
pub use switch_variables::SwitchVariables;
pub use weather_variables::WeatherVariables;
pub use woolworths_variables::WoolworthsVariables;
