- id: LIVING_ROOM
  source: { zigbee: "0x00158d008b8798a7" }
- id: BATHROOM
  source: { zigbee: "0x00158d008b879b53" }
- id: BEDROOM
  source: { zigbee: "0xb0c7defffef6a9be" }
- id: OUTDOOR
  source: { zigbee: "0x54ef441000ee2ca3" }
- id: LIVING_ROOM_MTR
  source: { esphome: { node: apollo-mtr-1-livingroom } }
- id: HALLWAY_PLANT
  source: { esphome: { node: apollo-plt-1-hallway } }
