"0x00158d008bbe0316":
  name: Small Switch
  actions:
    single:
      - type: light
        device: desk_lamp
        state: TOGGLE

"0x64028ffffe638218":
  name: Control Switch
  actions:
    on:
      - type: light
        device: ceiling_light
        state: ON

    off:
      - type: light
        device: ceiling_light
        state: OFF

    brightness_move_up:
      - type: light
        device: ceiling_light
        state: INCREASE_BRIGHTNESS
        value: 75

    brightness_move_down:
      - type: light
        device: ceiling_light
        state: DECREASE_BRIGHTNESS
        value: 75

    brightness_stop:
      - type: light
        device: ceiling_light
        state: STOP_BRIGHTNESS

    arrow_right_hold:
      - type: light
        device: ceiling_light
        state: INCREASE_COLOUR_TEMPERATURE
        value: 120

    arrow_left_hold:
      - type: light
        device: ceiling_light
        state: DECREASE_COLOUR_TEMPERATURE
        value: 120

    arrow_left_release:
      - type: light
        device: ceiling_light
        state: STOP_COLOUR_TEMPERATURE

    arrow_right_release:
      - type: light
        device: ceiling_light
        state: STOP_COLOUR_TEMPERATURE

    arrow_left_click:
      - type: light
        device: ceiling_light
        state: SET_BRIGHTNESS
        value: 50

    arrow_right_click:
      - type: light
        device: ceiling_light
        state: SET_BRIGHTNESS
        value: 254
