apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-web
  namespace: home-gateway
spec:
  selector:
    matchLabels:
      app: home-web
  replicas: 1
  template:
    metadata:
      labels:
        app: home-web
    spec:
      containers:
        - name: home-web
          image: home-web:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
