apiVersion: v1
kind: Service
metadata:
  name: home-web
  namespace: home-gateway
spec:
  selector:
    app: home-web
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
