apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: unifi-proxy-secret
  namespace: home-gateway
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: home-gateway-t54-s
        envSlug: prod
        secretsPath: "/unifi-proxy"
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedSecretReference:
    secretName: unifi-proxy-managed-secrets
    secretNamespace: home-gateway
    creationPolicy: "Owner"
