apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-proxy
  namespace: home-gateway
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: unifi-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: unifi-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: inf-k8s.net/location
                    operator: In
                    values:
                      - perth
      containers:
        - name: unifi-proxy
          image: unifi-proxy:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: FLIPT_URL
              value: http://flipt.flipt.svc.cluster.local:8080
          envFrom:
            - secretRef:
                name: unifi-proxy-managed-secrets
          ports:
            - containerPort: 3000
