apiVersion: v1
kind: Service
metadata:
  name: unifi-proxy
  namespace: home-gateway
spec:
  selector:
    app: unifi-proxy
  ports:
    - name: proxy
      protocol: TCP
      port: 80
      targetPort: 8001
