pub mod auth_query;
pub mod energy_query;
pub mod entities_query;
pub mod home_assistant_query;
pub mod jellyfin_query;
pub mod solar_query;
pub mod weather_query;
pub mod woolworths_query;
pub mod workflows_query;
