# yaml-language-server: $schema=../schemas/devices.schema.json
- id: env-living-room
  room: living-room
  transport: zigbee
  address: "0x00158d008b8798a7"
  model: lumi_wsdcgq11lm
  roles:
    - type: environment
      config: { id: living-room, name: Living Room }
      capabilities: [temperature, humidity, pressure]
    - type: battery

- id: env-bathroom
  room: bathroom
  transport: zigbee
  address: "0x00158d008b879b53"
  model: lumi_wsdcgq11lm
  roles:
    - type: environment
      config: { id: bathroom, name: Bathroom }
      capabilities: [temperature, humidity, pressure]
    - type: battery

- id: env-bedroom
  room: bedroom
  transport: zigbee
  address: "0xb0c7defffef6a9be"
  model: ikea_e2112
  roles:
    - type: environment
      config: { id: bedroom, name: Bedroom }
      capabilities: [temperature, humidity, pm25, voc_index]

- id: env-outdoor
  room: outdoor
  transport: zigbee
  address: "0x54ef441000ee2ca3"
  model: aqara_wsdcgq12lm
  roles:
    - type: environment
      config: { id: outdoor, name: Outdoor }
      capabilities: [temperature, humidity, pressure]
    - type: battery
