# yaml-language-server: $schema=../schemas/devices.schema.json
- id: living-room-tv
  state: enabled
  room: living-room
  transport:
    type: home_assistant
    address: media_player.living_room_tv
  model: media_player
  roles:
    - type: media_player
      config:
        name: Living Room TV

- id: living-room-speaker
  state: enabled
  room: living-room
  transport:
    type: esphome_native_api
    address: apollo-cast-1-livingroom.iot
  model: apollo_cast_1
  roles:
    - type: light
      config: { name: Living Room Speaker }
    - type: media_player
      config:
        name: Living Room Speaker
