# yaml-language-server: $schema=../schemas/devices.schema.json
- id: hallway-plant
  state: disabled
  room: hallway
  transport:
    type: mqtt
    address: apollo-plt-1-hallway
  model: apollo_plt_1
  roles:
    - type: environment
      config:
        id: hallway-plant
        name: Hallway Plant
    - type: plant
      config: { id: hallway-plant }

- id: living-room-plant
  state: enabled
  room: living-room
  transport:
    type: mqtt
    address: apollo-plt-1b-livingroom
  model: apollo_plt_1b
  roles:
    - type: environment
      config:
        id: living-room-plant
        name: Living Room Plant
    - type: plant
      config: { id: living-room-plant }
    - type: battery
