# yaml-language-server: $schema=../schemas/devices.schema.json
- id: plant-plt1b-1
  aliases: [living-room-plant]
  state: enabled
  room: living-room
  transport:
    type: mqtt
    address: apollo-plt-1b-livingroom
  model: apollo_plt_1b
  roles:
    - type: environment
      config:
        name: Living Room Plant
    - type: plant
      config: { name: Living Room Plant }
    - type: battery
