# yaml-language-server: $schema=../schemas/devices.schema.json
- id: presence-mtr1-1
  aliases: [livingroom-motion]
  state: enabled
  room: living-room
  transport:
    type: esphome_native_api
    address: apollo-mtr-1-livingroom.iot
  model: apollo_mtr_1
  roles:
    - type: light
      config:
        name: Living Room MTR-1 RGB
    - type: presence
      config:
        name: Living Room Motion
    - type: environment
      config:
        name: Living Room

- id: presence-fp1e-1
  aliases: [closet-presence]
  state: enabled
  room: bedroom
  transport:
    type: mqtt
    address: "0x54ef441000dbc81c"
  model: aqara_fp1e
  roles:
    - type: presence
      config: { name: Closet Presence Sensor }
