# yaml-language-server: $schema=../schemas/devices.schema.json
- id: roborock
  state: enabled
  room: dining-room
  transport:
    type: home_assistant
    address: vacuum.robot
  model: roborock
  watchdog: { timeout: 7d }
  roles:
    - type: robot_vacuum
      config:
        name: Roborock
    - type: battery

- id: valetudo
  state: enabled
  room: spare-room
  transport:
    type: mqtt
    address: rockrobo
  model: valetudo
  watchdog: { timeout: 7d }
  roles:
    - type: robot_vacuum
      config:
        name: Vacuum
    - type: battery
