name: Branch build eink-display-firmware

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - eink-display-firmware/**
      - .github/workflows/branch-build-eink-display-firmware.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: esp-rs/xtensa-toolchain@ec6d36527049a7f4fb2cb0c1a644668c1bb8a2a4 # v1.7
        with:
          buildtargets: esp32s3
          ldproxy: true
      - name: Build
        run: cargo build --release
        working-directory: eink-display-firmware
